import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{ height: "100px", background: "red" }}>
          <div>
            <Link href="/">Home</Link>
            <Link href="/portfolio">Portfolio</Link>
          </div>
          <div>
            <Link href="/convertor">Convertor</Link>
            <Link href="/coins">Coins</Link>
          </div>
          <button>Compare</button>
        </div>
        {children}
      </body>
    </html>
  );
}
